# Generated by Django 5.1.6 on 2025-03-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agent_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=50)),
                ('agent_type', models.CharField(max_length=50)),
                ('agent_description', models.CharField(max_length=50)),
                ('agent_status', models.CharField(max_length=50)),
                ('agent_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
