# Generated by Django 5.1.6 on 2025-03-07 01:12

import builtins
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_model',
            name='agent_lore',
            field=models.TextField(default=datetime.datetime(2025, 3, 7, 1, 12, 27, 553832, tzinfo=datetime.timezone.utc), max_length=builtins.max),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent_model',
            name='agent_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
