# Generated by Django 5.1.6 on 2025-03-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_news_api', '0002_article_mlmodel_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='in_validation_set',
            field=models.BooleanField(default=False),
        ),
    ]
